github/issue-metrics

- issue_metrics.py
- test_issue_metrics.py
Improves test coverage by refactoring logic from the `main()` into `get_per_issue_metrics()`, then adds a test for the `get_per_issue_metrics()` function.
> improve test coverage

- issue_metrics.py
fixes https://github.com/github/issue-metrics/issues/24
> fix: count reviews as responses

- README.md
Update docs for discussions searching with documentation links, corrected syntax for `type:discussions`, and a complex search example.
> Update docs for discussions searching

- .env-example
- README.md
- markdown_writer.py
- test_markdown_writer.py
> feat: Configurable column hiding

- .gitignore
- README.md
- issue_metrics.py
- json_writer.py
- test_json_writer.py
- test_markdown_writer.py
> feat: add JSON output

- .env-example
- .pylintrc
- README.md
- classes.py
- issue_metrics.py
- json_writer.py
- labels.py
- markdown_writer.py
- requirements.txt
- test_issue_metrics.py
- test_json_writer.py
- test_labels.py
- test_markdown_writer.py
fixes #41
Adds option to specify a list of `LABELS_TO_MEASURE`. ie. `LABELS_TO_MEASURE = "bug,enhancement,bogus"`
Output then adds time spent in label and the average. ie (see below)
| Metric | Value |
| --- | ---: |
| Average time to first response | 4 days, 6:28:54.625000 |
| Average time to close | 15 days, 3:41:37.090909 |
| Average time to answer | None |
| Average time spent in bug | 49 days, 1:49:59 |
| Average time spent in enhancement | 46 days, 0:39:46 |
| Average time spent in bogus | None |
| Number of items that remain open | 0 |
| Number of items closed | 11 |
| Total number of items created | 11 |
| Title | URL | Time to first response | Time to close | Time to answer | Time spent in bug | Time spent in enhancement | Time spent in bogus |
| --- | --- | --- | --- | --- | --- …
> feat: add time in labels

- issue_metrics.py
> bug: add exception handling

- README.md
> docs: Add team assignment

- README.md
The token used to request the team members name needs to have permissions to access that data. This pull request adds documentation to guide users in creating a properly permissioned token for use in this step.
> fix: docs to set token when getting team members

- issue_metrics.py
> fix: rm unwanted check for repo and owner

- .github/release-drafter.yml
Currently the release drafter is not properly incrementing the version numbers and is creating extra manual work. This is caused by the configuration file changed in this pull request not looking for the labels that this project actually uses. 
This pull request changes the label to match the ones used in this project.
> fix: release drafter to use proper labels

- .pylintrc
- markdown_writer.py
- test_markdown_writer.py
> Add reference to action in report

- .env-example
- README.md
- issue_metrics.py
- test_time_to_first_response.py
- time_to_first_response.py
ref. #65 
- Users listed in the `IGNORE_USERS` environment variable are now excluded from Time to First Response calculations.
- update README
The user who wrote the comment can be got by the following API.
- [issues.comment.IssueComment.user](https://github3.readthedocs.io/en/latest/api-reference/issues.html#github3.issues.comment.IssueComment.user)
- [github3.users.ShortUser.login](https://github3.readthedocs.io/en/latest/api-reference/users.html#github3.users.ShortUser.login)
> feat: Filter Out CI User Responses from Time to First Response

- markdown_writer.py
- test_labels.py
- test_markdown_writer.py
Somehow I managed to create a series of issues last month (I assume some weird copy-paste thing) that contained `\r` at the end of their titles. For example, [this pull request](https://api.github.com/repos/martincostello/update-static-assets/pulls/282), of which here's a snippet:
```jsonc
{
"url": "https://api.github.com/repos/martincostello/update-static-assets/pulls/282",
"id": 1454674049,
"node_id": "PR_kwDOHxs9d85WtJCB",
"html_url": "https://github.com/martincostello/update-static-assets/pull/282",
"number": 282,
"state": "closed",
"title": "Add actionlint\r", // <-- No idea how I managed to do this!
"user": {
"login": "martincostello"
}
}
```
This then causes the Markdown table rendering to break ([example](https://github.com/martincostello/github-automation/actions/runs/5735630789), …
> Trim issue titles

- issue_metrics.py
Resolving #90 
Simply checks the GITHUB_SERVER_URL environment variable, if it's set to github.com it will use the default login, otherwise it uses the GitHub Enterprise Server specific connection function.
Validated against my company's GitHub Enterprise Server instance, can't really show the output because of the proprietary nature of how the logs look. If there's a good bit of evidence you want for that that I can provide, let me know.
> Authenticate to GitHub Enterprise Server instances

- README.md
resolved #49 
- added an example to the README. This consolidates the metrics from multiple repos into a single report.
This example is working well, but there may be some potential problems. These might become challenges in the future.
- Unexpected references might occur and be treated as spam (as shown in the example I provided in [the issue](https://github.com/github/issue-metrics/issues/49#issuecomment-1662841517)).
- The use of the `chown` command within the workflow might pose a security risk. (I'm not a security expert, so I don't know the details, but...)
- The workflow has become a bit verbose. It might be more considerate to provide functionality to make it shorter.
- Including private repos might be a bit challenging. Is there a good way to deal with this?
> docs: Add example that demonstrates multiple search queries

- test_time_to_first_response.py
- time_to_first_response.py
Right now time to first response on issues is calculated incorrectly as `first_review_comment_time` and `first_review_comment_time` are being overwritten by data from later comments.
> fix: fix time to first response

- issue_metrics.py
Fixed `per_page` parameter to follow to the API specifications.
The parameter of `per_page` is allowed under the value of 100 as below document.
https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#list-repository-issues
> Fix: Modified parameters to follow to API specifications

- test_time_to_first_response.py
- time_to_first_response.py
Ignore issue comments and pr comments made by the issue owner. #101
> feature: exclude  issue owner's comment

- README.md
close #26 
I have improved the example for collecting metrics from multiple repositories. Previously, separate queries were issued, but now it can be achieved with a single query.
It might be very beneficial to add examples using the "involve" operator. This might be implemented in a separate PR.
> docs: update: Ability to send a list of repos instead of just one

- README.md
Updates the `IGNORE_USERS` configuration to document how bots and Github apps can be ignored from the `time to first response` calculation.
> docs(readme): document how to ignore bots

- .pylintrc
- Makefile
close #112 
During the lint execution, certain folders have been excluded. This change brings about the following benefits:
- Those who develop this project might experience shorter lint execution times.
- The execution time of the CI performing the lint might be slightly reduced (though this will likely be minimal).
> update: Makefile, .pylintrc

- README.md
- issue_metrics.py
- test_time_to_first_response.py
- test_time_to_merge.py
- test_time_to_ready_for_review.py
- time_to_first_response.py
- time_to_merge.py
- time_to_ready_for_review.py
Excludes the time a pull request was in draft mode when calculating how long it was open for, and uses the time a PR was merged as the time the issue was closed.
* If an issue is a pull request, grab when it was marked as Ready for Review
* To measure this, it grabs the first 50 [events](https://docs.github.com/en/rest/issues/events?apiVersion=2022-11-28) and looks for one called "Ready for Review".
* If it can't find it, subsequent steps will assume the PR was never a draft and will just use the Created time
* `measure_time_to_first_response` now excludes comments/reviews made before the PR was marked as Ready for Review
* Instead of calling `measure_time_to_close`, PRs now use `measure_time_to_merge` which will key off of the Ready for Review time (if one was found)
If the user would …
> Feature: Ignore PR time spent as draft, measure PRs by merge time

- test_time_to_merge.py
- test_time_to_ready_for_review.py
- time_to_merge.py
- time_to_ready_for_review.py
fixing issues found by running `make lint`
> linting fixes

- README.md
- test_time_to_first_response.py
- time_to_first_response.py
Exclude bot's comment from "Time to first response".
I believe that bots in GitHub actions often respond faster than users, so it's hard to imagine a use case where measuring the time it takes for a bot to respond would be useful.
> Exclude bot's comment from "Time to first response"

- README.md
- requirements.txt
When running `make test` for the first time on a machine not regularly used for building and testing python code chances are high that pytest and pytest-cov aren't installed. This add them as a dependency to requirements.txt.
Also adding information on minimum python version to run the code. With python3.10 I ran into the error message
`TypeError: Parameters to generic types must be types. Got <module 'github3.issues.event'`
With python3.11 this error was gone.
> Documentation: Add required python version to docs and test deps.

- README.md
- classes.py
- issue_metrics.py
- json_writer.py
- markdown_writer.py
- test_issue_metrics.py
- test_json_writer.py
- test_labels.py
- test_markdown_writer.py
- test_time_to_answer.py
- test_time_to_close.py
- test_time_to_first_response.py
close #128 
I have added an author column to each issue. As seen in the original issue and this simple sample, it now displays the user who created the issue. In the original issue, there is an `@`, but I decided not to include it as it could potentially trigger numerous notifications due to mentions.
```markdown
| Title | URL | Author | Time to first response | Time to close | Time to answer | Time spent in waiting-for-review | Time spent in waiting-for-manager |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Monthly issue metrics report | https://github.com/Okabe-Junya/sandbox/issues/249 | github-actions[bot] | None | None | None | None | None |
```
- The attributes of the IssueWithMetrics class have been modified. Therefore, this PR involves somewhat extensive changes.
- Obtaining …
> feat: add author column

- README.md
Documentation fixes in the main README.md.
- Some rewording in the first sentence, highlighting that the output of the GHA is a GitHub issue.
- minor bug fix (double space)
- minor cosmetics fixes in the markdown (not visible for the general readers, just for people reading the markdown)
- I am also leaving one question as a comment in this PR, about an area where I am not sure how the `*` footnotes are supposed to be formatted
> Docs improvements in README.md

- README.md
- docs/search-query.md
This fixes:
@zkoppert looks like merging this has accidentally done some of the changes that we did in https://github.com/github/issue-metrics/pull/137 prior to this.
_Originally posted by @spier in https://github.com/github/issue-metrics/issues/139#issuecomment-1760199843_
- Fix overwrite of pr's that were merged in at a similar time.
> Fix README collisions

- issue_metrics.py
- labels.py
- markdown_writer.py
- requirements.txt
- test_issue_metrics.py
- test_labels.py
- test_markdown_writer.py
- test_time_to_answer.py
- test_time_to_close.py
- test_time_to_first_response.py
- time_to_answer.py
- time_to_close.py
- time_to_first_response.py
This commit switches code for computing averages to using numpy.
This is a first step towards supporting more than one statistic for summarizing lists of times for state change of issues. #84 
Averages are easy to compute but sensitive to outliers. In particular when thinking of SLAs for times for first responses it is often more helpful to look at median, quartiles or even 90th percentile.
> Support more than one statistic for summarizing time lists

- README.md
In #139 the references to the footnotes were accidentally removed.
I added back in the references to the footnotes in the top-most table that explains the different metrics.
Also suggested some rewording for better readability.
> [docs] Add back references to footnotes

- README.md
close #142 
- add `Getting Started` section in README
Is the term `Quick Start` really appropriate? There are similar expressions like:
- `Getting Started`
- `Usage`
- `Tutorial`
- `Simple Example/Basic Example`
- ...
> docs: add `Getting Started` section in README

- labels.py
- time_to_answer.py
- time_to_close.py
- time_to_first_response.py
remove sub-seconds from stats. Addresses part of #144
> remove sub-seconds from stats

- .vscode/settings.json
- markdown_writer.py
- test_markdown_writer.py
Addresses part of #144
Split out the summary table into 2 tables in order to improve readability
> Split out the summary table into 2 tables

- markdown_writer.py
- test_markdown_writer.py
Related to https://github.com/github/issue-metrics/issues/156
- always printing the title and search query even when the results are empty
> always print the title and search query

- json_writer.py
- markdown_writer.py
- test_json_writer.py
For the moment, `med` and `90p` are not supported, but the bug where `avg` is not output correctly has been addressed.
> fix: #161 Incorrect output values in issue_metrics.json

- config.py
- issue_metrics.py
- markdown_writer.py
- test_issue_metrics.py
- test_markdown_writer.py
Refactor Environment Variable Retrieval Across Application - Resolves #168
This PR addresses issue #168 by refactoring the application to consistently use the `get_env_vars()` function for environment variable retrieval. 
- Added a new module in `config.py`, introducing the following components:
- `EnvVars`: A class that encapsulates all environment variables required in the script.
- `get_env_vars()`: A function to retrieve an instance of `EnvVars` populated with environment variables.
> refactor(get_env_vars): use get_env_vars() for consistent env variable retrieval

- Dockerfile
- issue_metrics.py
I found some logic in `issue_metrics.py` that is duplicating environment variable processing already happening via `get_env_vars()` in `config.py`, which was introduced in #171.
https://github.com/github/issue-metrics/blob/ebc6a99b31b69b73a26678b9ac5a6ebbc021c663/config.py#L61-L71
Duplicate logic:
https://github.com/github/issue-metrics/blob/ebc6a99b31b69b73a26678b9ac5a6ebbc021c663/issue_metrics.py#L260-L264
https://github.com/github/issue-metrics/blob/ebc6a99b31b69b73a26678b9ac5a6ebbc021c663/issue_metrics.py#L140-L141
Removing this duplicate logic fixes #180.
> Remove duplicate logic

- .devcontainer/devcontainer.json
This pull request creates a Dev Container configuration file and utilizes the existing Dockerfile to install the proper dependencies. This makes using, testing, and contributing via Codespaces much easier.
> Create Dev Container configuration

- most_active_mentors.py
- test_time_to_first_response.py
- time_to_first_response.py
Check that `comment_created_at` is valid datetime.
`comment_created_at` might not exist if reviews were still pending when PR was merged. This would cause a TypeError in future comparisons: Issue #173.
> Handle Pending Review Case

- .github/linters/.jscpd.json
- .gitignore
Helps us merge #240 
- they do not have the alternative to include (that list would be *.py)
We have a duplicate clone in labels.py right now but beyond the scope of this change IMO
> fix: add config for jscpd linter

- .github/workflows/release.yml
Seems the [`Unexpected status from HEAD request to <url>: 400 Bad Request`](https://github.com/github/issue-metrics/actions/runs/8758107284/job/24038180863#step:5:1024) is an intermittent error in GitHub Actions and pushing to ghcr that can be solved by using moby/buildkit via
https://github.com/docker/build-push-action/issues/761#issuecomment-1383822381
Going to try this with latest release of moby/buildkit to see if it fixes it
> fix: release container image build

- .github/dependabot.yml
- requirements-test.txt
Closes #252
Closes #251
Add commit-message.prefix config option to dependabot so that dependabot pull request titles pass our new PR Title Linting workflow
> chore(deps): update dependabot config to include pr prefixes

- .github/pull_request_template.md
- auth.py
- issue_metrics.py
- most_active_mentors.py
- test_auth.py
- test_issue_metrics.py
- test_most_active_mentors.py
Currently we are still trying to use the GH_TOKEN env var when making api/graphql calls even after authenticating with a GitHub App Installation. This change fixes that.
Also fixed a few other things while in here:
> fix: use GitHub App token when authed with GitHub App

- issue_metrics.py
- test_issue_metrics.py
fixes #256 
This pull request includes changes to the `issue_metrics.py` and `test_issue_metrics.py` files. The changes are primarily aimed at allowing the `search_issues` function to search for issues in multiple GitHub repositories at once. This is achieved by modifying the function to accept a list of owners and repositories, instead of a single owner and repository.
> fix: handle multiple repos in search query

- .github/linters/.flake8
- .gitignore
- README.md
- docs/dealing-with-large-issue-metrics.md
- issue_metrics.py
- markdown_helpers.py
- test_markdown_helpers.py
fixes #258 
This pull request introduces changes to handle large `issue_metrics.md` files that exceed GitHub's maximum issue body character limit. The changes include splitting large markdown files into smaller ones, adding new helper functions to handle these operations, and updating the `README.md` with a link to a new document explaining how to deal with large markdown files.
> feat: Split markdown files when larger than max issue body size

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/contributor_report.yaml
- .github/workflows/docker-image.yml
- .github/workflows/linter.yaml
- .github/workflows/major-version-updater.yml
- .github/workflows/pr-title.yml
- .github/workflows/python-package.yml
- .github/workflows/release.yml
- .github/workflows/scorecard.yml
Closes #268, Closes #269, Closes #270, Close #271, Close #272
To minimize the number of pull requests we get from dependabot, using groups will help with this.  Still want major semver changes to be single PRs so that stand out and we pay particular attention to them.
> chore: group dependabot dependency updates for minor/patch updates

- issue_metrics.py
- test_issue_metrics.py
Rate limiting of the Github search API is causing a 403 Authentication Error for some users. Issues #217 and potentially #166 are related.
The github3 SearchIterator object has a ratelimit_remaining property that is used to measure if we are near API rate limits. If remaining requests are low (<5), there is a 1 minute delay to refresh requests with exponential increases in delays ([corresponding rate limit docs](https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#rate-limit)). This is consistent with Github's recommended [best practice guidelines](https://docs.github.com/en/rest/using-the-rest-api/best-practices-for-using-the-rest-api?apiVersion=2022-11-28#handle-rate-limit-errors-appropriately) since the github3 wrappers prevent us from easily accessing the retry headers.
> feat: Avoid API Rate-Limiting

- labels.py
- test_labels.py
Address case where negative time for "time label applied" is reported for labels that have at some point been both "labeled" and "unlabeled" on a given issue (https://github.com/github/issue-metrics/issues/282)
> fix: Negative time reported for "time label applied" measurement

- .github/workflows/release.yml
Release fails if pull request is from a fork currently because we can't access the labels on the forked pull request which helps us determine semver for next release.
Saw this after merging https://github.com/github/issue-metrics/pull/283 (from a fork)
Add pull_request_target to release action workflow
I am not worried about the security implications with us checking out the forked pull requests code.  This action only fires after a merge to main so this means the pull request code has been reviewed by a maintainer.  We are post-CI/code run.
> fix: allow access to forked pull request labels for release

- .github/workflows/auto-labeler.yml
- .github/workflows/linter.yaml
- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .github/workflows/scorecard.yml
- config.py
- test_config_get_bool.py
> chore: standardize github action types

- time_to_ready_for_review.py
fixes https://github.com/github/issue-metrics/issues/322
This pull request changes the `get_time_to_ready_for_review` function in the `time_to_ready_for_review.py` file. The change introduces error handling to deal with potential `TypeError` exceptions that might occur when processing review events. If such an error occurs, a message is printed to inform the user that the issue might contain a ghost user, and `None` is returned.
> fix: catch error that occurs when ghost usre creates an event.

- time_to_first_response.py
related to https://github.com/github/issue-metrics/pull/325. This PR handles the same issue as the previous PR, but this time it catches review comments (previous pr handled generic comments not attached to a review) with no valid user. This is important because it prevents the code from breaking when a review contains a ghost user.
> fix: Catch review comments with no valid user

- README.md
- config.py
- issue_metrics.py
- markdown_writer.py
- test_config.py
- test_markdown_writer.py
Adds a new env var which allows you to specify non-mentioning links to the issues.
Non-mentioning links are possible using this [workaround](https://github.com/orgs/community/discussions/23123)
The links still work as before, but they do not cause a notification in the desitnation repository, which helps reduce "spam" there.
> feat: add non-mentioning links option

- issue_metrics.py
Had too many arguments in write_to_json call
> fix: too many arguments to write_to_json

- .github/workflows/major-version-updater.yml
Remove more general part of duplicate actions permissions. Fixes https://github.com/github/issue-metrics/security/code-scanning/11
Relevant documentation: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
Remove `contents: write` at the top level
> fix: Remove more general part of duplicate actions permissions

- README.md
Add documentation for developers on how to set up this codebase to run locally 
Add instructions to README on how to get started running the codebase if contributing.
Closes: https://github.com/github/issue-metrics/issues/384
> docs: developer setup instructions to run codebase

- README.md
- docs/verify-token-access-to-repository.md
Offering a little script to help verify token access to a repository.
When I was going through the repo setup and figuring out how to use this action on my own, I ran into some confusion around the GitHub PAT token access, especially since our `Github` access is behind SAML SSO.
Add a how-to page on checking the token access and a link to it via the README.
> docs: instructions on verifying token access to a repository

- .github/workflows/python-package.yml
python-setup takes care of the pip install and upgrade. This should also improve our OSSF score
This pull request includes a small update to the GitHub Actions workflow file for setting up the Python environment. The change updates the version of the `setup-python` action to ensure compatibility with the latest features and improvements.
> chore: Remove unneeded pip install

- issue_metrics.py
- markdown_writer.py
- test_issue_metrics.py
Main goal: Ensure that report name, issue title, and search query the pass through properly when the search query results are empty. 
Minor addition: I also improved the readability of the `write_to_markdown` function calls by using named parameters instead of positional parameters.
Example of markdown report before and after this code change:
Before:
```markdown
no issues found for the given search criteria
_This report was generated with the [Issue Metrics Action](https://github.com/github/issue-metrics)_
```
After:
```markdown
no issues found for the given search criteria
_This report was generated with the [Issue Metrics Action](https://github.com/github/issue-metrics)_
Search query used to find these items: `repo:github/issue-metrics is:issue created:2024-10-01..2024-10-14`
```
> fix: pass through report name, issue title, and search query when report is empty

- issue_metrics.py
- search.py
- test_issue_metrics.py
- test_search.py
This pull request refactors the `issue_metrics.py` module by moving the `search_issues` and `get_owners_and_repositories` functions to a new `search.py` module. Additionally, it moves the corresponding unit tests to their own test file to follow the current style.
The purpose of doing this is to improve readability of `issue_metrics.py` by separating out the search specific functions.
- Move `search_issues` and `get_owners_and_repositories` functions to `search.py`
- Move corresponding unit tests to `test_search.py
- Fix imports and pylint issues
> refactor: Move search functions and tests to their own files

- test_auth.py
improve auth test coverage by adding invalid and failed app install tests
This pull request adds new test cases to the `test_auth.py` file to improve the coverage and robustness of the authentication functions. The most important changes include importing the `requests` library, adding a test for handling request failures, and adding a test for handling invalid credentials.
> test: improve auth test coverage

- discussions.py
This pull request modifies the GraphQL API endpoint URL construction in the `discussions.py` file. The change ensures proper handling of GitHub Enterprise Server (GHES) GraphQL API endpoints.
* Removed `/v3` from the API endpoint construction as GraphQL APIs in GHES use `/api/graphql` instead of `/api/v3/graphql`
* This fixes 404 errors when attempting to access GraphQL endpoints on GHES instances
According to the [GitHub Enterprise Server GraphQL documentation](https://docs.github.com/en/enterprise-server@3.15/graphql/guides/introduction-to-graphql#discovering-the-graphql-api), the correct endpoint format is `http(s)://HOSTNAME/api/graphql`. Unlike REST APIs which use versioning (`/api/v3`), GraphQL APIs in GHES do not include version numbers in the URL path.
> fix(GHES): Remove versioning from GraphQL API endpoint URL in discussions.py

- issue_metrics.py
- test_time_in_draft.py
- time_in_draft.py
Fixes: #417 
- Updated the time in draft to work even if a pr has been changed from `ready for review` to `draft` by using the events from the issues object. 
- Also updated the test cases to reflect and test the new changes.
> fix: Update time in draft to account for edge cases and update tests

- discussions.py
- test_discussions.py
This pull request includes enhancements to the `get_discussions` function in `discussions.py` to support pagination and improvements to the corresponding tests in `test_discussions.py`. The most important changes include adding pagination to the GraphQL query, handling pagination in the function, and updating the tests to cover these scenarios.
Closes #44
- Add pagination support to GitHub Discussions Query.
Respective Issue: #44
> feat(discussions): refactor get_discussions function for pagination support

- docs/authenticating-with-github-app-installation.md
The `GITHUB_` prefix is no longer supported in GitHub Actions secrets, so I updated the relevant documentation in `docs/authenticating-with-github-app-installation.md`.
Fixes #436.  
- Updated `docs/authenticating-with-github-app-installation.md` to clarify that the `GITHUB_` prefix is no longer supported in GitHub Actions secrets.  
- No other files or configurations were modified in this PR.  
- I verified the changes by running workflows in my personal repository, and all Actions completed successfully.
> fix: The GITHUB_ prefix was unusable

- issue_metrics.py
Fixes https://github.com/github/issue-metrics/pull/460#issuecomment-2616135404
Looked at the [ReST API for Get an Issue](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#get-an-issue) and the response confirms it should be `created_at` and not `createdAt`
> fix: use correct created_at issue api attribute

- issue_metrics.py
- markdown_writer.py
- test_issue_metrics.py
Resolves #479 
When the `OUTPUT_FILE` env variable is specified in a calling Action, it is used everywhere except when checking for file size and splitting into multiple files. The default `issue_metrics.md` name was hardcoded.
This PR updates the script to use the provided `output_file` name and uses that naming as the basis for the smaller file names.
> fix: Use the `output_file` variable  in `issue_metrics.py`

- issue_metrics.py
- test_issue_metrics.py
This should fix the regression from #480.
Set a default filename for the output file in case it is empty.
> fix: Set default filename, when output file is empty

- issue_metrics.py
- test_config.py
- test_issue_metrics.py
- test_markdown_writer.py
Fixes #489
We union dict and github3.search.IssueSearchResult types but their created at attributes are accessed differently.
issue["createdAt"] for dict
issue.issue.created_at for github3.search.IssueSearchResult
> fix: handle created_at with diff types

- Dockerfile
- json_writer.py
- test_json_writer.py
Additional fixes for https://github.com/github/issue-metrics/issues/489
> fix: ensure created_at shows up in json

- issue_metrics.py
- test_markdown_writer.py
- fixes https://github.com/github/issue-metrics/issues/512
> feat: consider GH_ENTERPRISE_URL env in markdown author URL

- search.py
Print api error messages so user's can solve problems
> feat: pass through api error messages

- labels.py
Fix typo from `occured` to `occurred`
> fix: typo from `occured` to `occurred`
